# ------------------------------------------------------------------------
# Copyright (c) 2023 CandleLabAI. All Rights Reserved.
# ------------------------------------------------------------------------
# general settings
name: LIVENet
model_type: LLIE

datasets:
  train:
    name: Lolv1
    low_images: ../data/our485/low
    normal_images: ../data/our485/high

    img_size_h: 512
    img_size_w: 512

    # data loader
    use_shuffle: true
    batch_size: 2

    num_workers: 2

  val:
    name: Lolv1
    low_images: ../data/eval15/low
    normal_images: ../data/eval15/high

    img_size_h: 512
    img_size_w: 512

    use_shuffle: false
    batch_size: 1

    num_workers: 2

model:
  gray:
    in_nc: 3
    out_nc: 1
  tranmission_map:
    in_nc: 3
    out_nc: 1
  atmospheric_light:
    in_nc: 3
    out_nc: 3
  refiner:
    in_nc: 3
    out_nc: 3
  channel_prior_kernel: 1
  tmin: 0.15
  omega: 0.75
  alpha: 0.4

# path
path:
  checkpoint_gen_network: ../checkpoints/best_gen.pth
  checkpoint_ref_network: ../checkpoints/best_refine.pth
  log_file: ../logs/app.log
  train_logs: ../logs/runs/train
  val_logs: ../logs/runs/val

# training settings
train:
  manual_seed: 42
  optim:
    type: Adam
    lr: 3e-4
  epochs: 1000
  save_checkpoint: true
  load_checkpoint: false

  metrics:
    psnr: true
    ssim: true